project:
  type: website
  output-dir: docs

website:
  title: "R4SPISE2024"
  navbar:
    left:
      - href: pages/A_Data.qmd
        text: The Wines
      - href: pages/B_PCA.qmd
        text: PCA
      - href: pages/C_PLSC.qmd
        text: PLSC
      - href: pages/D_MFA.qmd
        text: MFA
      - href: pages/E_PLSR.qmd
        text: PLS-R
      - href: about.qmd
        text: About us
      - icon: github
        href: https://github.com/vguillemot/R4SPISE2024
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
